In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('C:/Users/Anthony Christian/Desktop/Transactions Data/transactions.csv',low_memory = False,sep=';')

In [3]:
df.head()

,transaction_id,accountNumber,customerId,creditLimit,availableMoney,transactionDateTime,transactionAmount,merchantName,acqCountry,merchantCountryCode,...,isFraud,echoBuffer,currentBalance,merchantCity,merchantState,merchantZip,cardPresent,posOnPremises,recurringAuthInd,expirationDateKeyInMatch
0,5533441,733493772,733493772,5000,5000.0,2016-01-08T19:04:50,111.33,Lyft,US,US,...,True,NaN,0.0,NaN,NaN,NaN,False,NaN,NaN,False
1,5533442,733493772,733493772,5000,4888.67,2016-01-09T22:32:39,24.75,Uber,US,US,...,False,NaN,111.33,NaN,NaN,NaN,False,NaN,NaN,False
2,5533443,733493772,733493772,5000,4863.92,2016-01-11T13:36:55,187.4,Lyft,US,US,...,False,NaN,136.08,NaN,NaN,NaN,False,NaN,NaN,False
3,5533444,733493772,733493772,5000,4676.52,2016-01-11T22:47:46,227.34,Lyft,US,US,...,True,NaN,323.48,NaN,NaN,NaN,False,NaN,NaN,False
4,5533445,733493772,733493772,5000,4449.18,2016-01-16T01:41:11,0.0,Lyft,US,US,...,False,NaN,550.82,NaN,NaN,NaN,False,NaN,NaN,False

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 641914 entries, 0 to 641913
Data columns (total 30 columns):
 #   Column                    Non-Null Count   Dtype
---  ------                    --------------   -----
 0   transaction_id            641914 non-null  int64
 1   accountNumber             641914 non-null  int64
 2   customerId                641914 non-null  int64
 3   creditLimit               641914 non-null  int64
 4   availableMoney            641914 non-null  object
 5   transactionDateTime       641914 non-null  object
 6   transactionAmount         641914 non-null  object
 7   merchantName              641914 non-null  object
 8   acqCountry                638001 non-null  object
 9   merchantCountryCode       641290 non-null  object
 10  posEntryMode              638569 non-null  float64
 11  posConditionCode          641627 non-null  float64
 12  merchantCategoryCode      641914 non-null  object
 13  currentExpDate            641914 non-null  object
 14  accountOpenDate           641914 non-null  object
 15  dateOfLastAddressChange   641914 non-null  object
 16  cardCVV                   641914 non-null  int64
 17  enteredCVV                641914 non-null  int64
 18  cardLast4Digits           641914 non-null  int64
 19  transactionType           641325 non-null  object
 20  isFraud                   641914 non-null  bool
 21  echoBuffer                0 non-null       float64
 22  currentBalance            641914 non-null  object
 23  merchantCity              0 non-null       float64
 24  merchantState             0 non-null       float64
 25  merchantZip               0 non-null       float64
 26  cardPresent               641914 non-null  bool
 27  posOnPremises             0 non-null       float64
 28  recurringAuthInd          0 non-null       float64
 29  expirationDateKeyInMatch  641914 non-null  bool
dtypes: bool(3), float64(8), int64(7), object(12)
memory usage: 134.1+ MB

In [5]:
df.dtypes

transaction_id                int64
accountNumber                 int64
customerId                    int64
creditLimit                   int64
availableMoney               object
transactionDateTime          object
transactionAmount            object
merchantName                 object
acqCountry                   object
merchantCountryCode          object
posEntryMode                float64
posConditionCode            float64
merchantCategoryCode         object
currentExpDate               object
accountOpenDate              object
dateOfLastAddressChange      object
cardCVV                       int64
enteredCVV                    int64
cardLast4Digits               int64
transactionType              object
isFraud                        bool
echoBuffer                  float64
currentBalance               object
merchantCity                float64
merchantState               float64
merchantZip                 float64
cardPresent                    bool
posOnPremises               float64
recurringAuthInd            float64
expirationDateKeyInMatch       bool
dtype: object

In [6]:
#Transform Data Types

#Transform Numerical
df['transactionAmount'] = pd.to_numeric(df['transactionAmount'],errors='coerce')
df['availableMoney'] = pd.to_numeric(df['availableMoney'],errors='coerce')
df['currentBalance'] = pd.to_numeric(df['currentBalance'],errors='coerce')

#Transform Date Time
df['transactionDateTime'] = pd.to_datetime(df['transactionDateTime'], format="%Y-%m-%dT%H:%M:%S")

In [7]:
df.isnull().sum()

transaction_id                   0
accountNumber                    0
customerId                       0
creditLimit                      0
availableMoney                 279
transactionDateTime              0
transactionAmount             1816
merchantName                     0
acqCountry                    3913
merchantCountryCode            624
posEntryMode                  3345
posConditionCode               287
merchantCategoryCode             0
currentExpDate                   0
accountOpenDate                  0
dateOfLastAddressChange          0
cardCVV                          0
enteredCVV                       0
cardLast4Digits                  0
transactionType                589
isFraud                          0
echoBuffer                  641914
currentBalance                 120
merchantCity                641914
merchantState               641914
merchantZip                 641914
cardPresent                      0
posOnPremises               641914
recurringAuthInd            641914
expirationDateKeyInMatch         0
dtype: int64

In [8]:
#Fill Missing Value

df['availableMoney'].fillna(df['availableMoney'].median(),inplace = True)
df['transactionAmount'].fillna(df['transactionAmount'].median(),inplace = True)
df['acqCountry'].fillna(df['acqCountry'].mode()[0],inplace = True)
df['merchantCategoryCode'].fillna(df['merchantCategoryCode'].mode()[0],inplace = True)
df['transactionType'].fillna(df['transactionType'].mode()[0],inplace = True)
df['posEntryMode'].fillna(df['posEntryMode'].mode()[0],inplace = True)

In [9]:
df.isnull().sum()

transaction_id                   0
accountNumber                    0
customerId                       0
creditLimit                      0
availableMoney                   0
transactionDateTime              0
transactionAmount                0
merchantName                     0
acqCountry                       0
merchantCountryCode            624
posEntryMode                     0
posConditionCode               287
merchantCategoryCode             0
currentExpDate                   0
accountOpenDate                  0
dateOfLastAddressChange          0
cardCVV                          0
enteredCVV                       0
cardLast4Digits                  0
transactionType                  0
isFraud                          0
echoBuffer                  641914
currentBalance                 120
merchantCity                641914
merchantState               641914
merchantZip                 641914
cardPresent                      0
posOnPremises               641914
recurringAuthInd            641914
expirationDateKeyInMatch         0
dtype: int64

In [11]:
df.describe()

,transaction_id,accountNumber,customerId,creditLimit,availableMoney,transactionAmount,posEntryMode,posConditionCode,cardCVV,enteredCVV,cardLast4Digits,echoBuffer,currentBalance,merchantCity,merchantState,merchantZip,posOnPremises,recurringAuthInd
count,6.419140e+05,6.419140e+05,6.419140e+05,641914.000000,641914.000000,641914.000000,641914.000000,641627.000000,641914.000000,641914.000000,641914.000000,0.0,641794.000000,0.0,0.0,0.0,0.0,0.0
mean,5.854398e+06,5.547701e+08,5.547701e+08,10697.210608,6654.155469,135.396502,9.114905,3.238367,557.199927,556.775160,4886.184043,NaN,4045.137565,NaN,NaN,NaN,NaN,NaN
std,1.853048e+05,2.546884e+08,2.546884e+08,11460.359133,9226.427265,146.909332,16.919556,9.680862,257.326204,257.402639,2859.053679,NaN,5945.809259,NaN,NaN,NaN,NaN,NaN
min,5.533441e+06,1.005471e+08,1.005471e+08,250.000000,-1244.930000,0.000000,2.000000,1.000000,100.000000,1.000000,0.000000,NaN,0.000000,NaN,NaN,NaN,NaN,NaN
25%,5.693919e+06,3.223192e+08,3.223192e+08,5000.000000,1117.762500,32.830000,2.000000,1.000000,334.000000,333.000000,2364.000000,NaN,503.190000,NaN,NaN,NaN,NaN,NaN
50%,5.854398e+06,5.438879e+08,5.438879e+08,7500.000000,3580.870000,86.230000,5.000000,1.000000,581.000000,580.000000,4873.000000,NaN,2152.635000,NaN,NaN,NaN,NaN,NaN
75%,6.014876e+06,7.862277e+08,7.862277e+08,15000.000000,8168.897500,189.030000,9.000000,1.000000,762.000000,761.000000,7267.000000,NaN,5006.760000,NaN,NaN,NaN,NaN,NaN
max,6.175354e+06,9.999853e+08,9.999853e+08,50000.000000,50000.000000,1825.250000,90.000000,99.000000,998.000000,998.000000,9998.000000,NaN,47496.500000,NaN,NaN,NaN,NaN,NaN

# Data Selection

In [12]:
df[['accountNumber','customerId','creditLimit']].head()

   accountNumber  customerId  creditLimit
0      733493772   733493772         5000
1      733493772   733493772         5000
2      733493772   733493772         5000
3      733493772   733493772         5000
4      733493772   733493772         5000

In [13]:
df.iloc[0]

transaction_id                          5533441
accountNumber                         733493772
customerId                            733493772
creditLimit                                5000
availableMoney                             5000
transactionDateTime         2016-01-08 19:04:50
transactionAmount                        111.33
merchantName                               Lyft
acqCountry                                   US
merchantCountryCode                          US
posEntryMode                                  5
posConditionCode                              1
merchantCategoryCode                  rideshare
currentExpDate                       01/04/2020
accountOpenDate                      03/08/2014
dateOfLastAddressChange              03/08/2014
cardCVV                                     492
enteredCVV                                  492
cardLast4Digits                            9184
transactionType                        PURCHASE
isFraud                                    True
echoBuffer                                  NaN
currentBalance                                0
merchantCity                                NaN
merchantState                               NaN
merchantZip                                 NaN
cardPresent                               False
posOnPremises                               NaN
recurringAuthInd                            NaN
expirationDateKeyInMatch                  False
Name: 0, dtype: object

In [14]:
#Filter data Fraud and Not

Fraud = df[df['isFraud']==True]

Valid = df[df['isFraud']==False]

# Pivoting

In [15]:
data = df[df['transactionType']=='PURCHASE']
pd.pivot_table(data,index = ['merchantCategoryCode','merchantCountryCode'],values = 'transactionAmount',aggfunc = 'mean').head(11)

                                          transactionAmount
merchantCategoryCode merchantCountryCode
airline              CAN                         120.453043
                     MEX                         178.147949
                     PR                          136.571667
                     US                          148.468147
auto                 CAN                         143.973704
                     MEX                         172.448085
                     PR                          205.022105
                     US                          149.723503
cable/phone          CAN                         140.793750
                     MEX                         102.668462
                     US                           98.246807

# CrossTab

In [16]:
pd.crosstab(df.merchantCategoryCode, df.posEntryMode, margins=True)

posEntryMode             2.0     5.0     9.0   80.0   90.0     All
merchantCategoryCode
airline                 2473    4007    3032    212    266    9990
auto                    2535    4124    3035    194    259   10147
cable/phone              298     592     536     19     45    1490
entertainment          17395   28002   20565   1428   1748   69138
fastfood               25214   41015   30440   2010   2517  101196
food                   17168   27490   20490   1396   1701   68245
food_delivery           1365    1956    1571      0     98    4990
fuel                    5483    8965    7009    449    660   22566
furniture               1905    3228    2314    166    200    7813
gym                      869    1103     691     38    173    2874
health                  3479    5940    4269    287    369   14344
hotels                  5666    9288    6894    453    578   22879
mobileapps              3694    5933    4344    290    353   14614
online_gifts            8322   13222    9977    684    840   33045
online_retail          40275   64970   48869   3312   4043  161469
online_subscriptions    2969    4484    3338    221    235   11247
personal care           4242    6876    4999    338    462   16917
rideshare              12547   20489   15233   1036   1269   50574
subscriptions           4690    7276    5587    388    435   18376
All                   160589  258960  193193  12921  16251  641914

# Categorical Encoding (Nominal Data)

In [18]:
df = pd.get_dummies(df, columns=['transactionType'])

In [19]:
df.head(8)

,transaction_id,transactionType_ADDRESS_VERIFICATION,transactionType_PURCHASE,transactionType_REVERSAL
0,5533441,0,1,0
1,5533442,0,1,0
2,5533443,0,1,0
3,5533444,0,1,0
4,5533445,1,0,0
5,5533446,0,1,0
6,5533447,0,1,0
7,5533448,1,0,0

# Categorical Data (Ordinal Data)

In [20]:
bins = [0, 250, 500, 750, 1000, 2000]
labels =['very low','low','moderate','high spending','very-high']
df['transactionLevel'] = pd.cut(df['transactionAmount'], bins,labels=labels)
df[['transactionAmount','transactionLevel']].head(8)

KeyError: 'transactionAmount'

In [21]:
bins = [0, 250, 500, 750, 1000, 2000]
labels =['very low','low','moderate','high spending','very-high']
df['transactionLevel'] = pd.cut(df['transactionAmount'], bins,labels=labels)
df.head()

KeyError: 'transactionAmount'

In [22]:
df.transactionLevel.fillna(df['transactionLevel'].mode()[0],inplace = True)

AttributeError: 'DataFrame' object has no attribute 'transactionLevel'

In [23]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
df["transactionLevelchanged"] = le.fit_transform(df["transactionLevel"])
df.head(7)

KeyError: 'transactionLevel'

In [24]:
df["transactionLevelnew"] = df['transactionLevel'].map({'very low':0,'low':1,'moderate':2,'high spending':3,'very-high':4})
df.head()

KeyError: 'transactionLevel'